theme: jekyll-theme-minimal
title: Academic Works
description: Collection of my academic works

collections:
    theses:
        output: true
        permalink: /:collection/:name
    articles:
        output: true
        permalink: /:collection/:name
